-- USUWANIE TABEL --
DROP TABLE DOKUMENTY CASCADE CONSTRAINTS PURGE;
DROP TABLE DOKUMENTYSZCZEGOLY CASCADE CONSTRAINTS PURGE;
DROP TABLE FIRMA CASCADE CONSTRAINTS PURGE;
DROP TABLE JEDNOSTKIMIARY CASCADE CONSTRAINTS PURGE;
DROP TABLE KONTRAHENCI CASCADE CONSTRAINTS PURGE;
DROP TABLE STATYSTYKI CASCADE CONSTRAINTS PURGE;
DROP TABLE STAWKAVAT CASCADE CONSTRAINTS PURGE;
DROP TABLE TOWARY CASCADE CONSTRAINTS PURGE;
DROP TABLE UZYTKOWNICY CASCADE CONSTRAINTS PURGE;
DROP TABLE ARCHIWUMKONTRAHENCI CASCADE CONSTRAINTS PURGE;
DROP TABLE ARCHIWUMTOWARY CASCADE CONSTRAINTS PURGE;
DROP TABLE ARCHIWUMUZYTKOWNICY CASCADE CONSTRAINTS PURGE;
DROP TABLE DOKUMENTY CASCADE CONSTRAINTS PURGE;
DROP TABLE DOKUMENTYSZCZEGOLY CASCADE CONSTRAINTS PURGE;

-- USUWANIE SEKWENCJI --
DROP SEQUENCE DOKUMENTY_SEQ;
DROP SEQUENCE DOKUMENTYSZCZEGOLY_SEQ;
DROP SEQUENCE JEDNOSTKIMIARY_SEQ;
DROP SEQUENCE KONTRAHENCI_SEQ;
DROP SEQUENCE STATYSTYKI_SEQ;
DROP SEQUENCE STAWKAVAT_SEQ;
DROP SEQUENCE TOWARY_SEQ;
DROP SEQUENCE UZYTKOWNICY_SEQ;
DROP SEQUENCE ARCHIWUMKONTRAHENCI_SEQ;
DROP SEQUENCE ARCHIWUMTOWARY_SEQ;
DROP SEQUENCE ARCHIWUMUZYTKOWNICY_SEQ;
DROP SEQUENCE ARCHIWUMDOKUMENTY_SEQ;
DROP SEQUENCE ARCHIWUMUDOKUMENTYSZCZEGOLY_SEQ;
