-- 1 --

CREATE TABLE DOKUMENTY(
ID int primary key,
IDKONTRAHENTA int not null,
IDUZYTKOWNIKA int not null,
NRFAKTURY varchar2(20) not null,
TYPPLATNOSCI varchar2(50) not null,
DATASPRZEDAZY date not null,
DATAFAKTURY date not null,
UWAGI varchar2(200)
);

-- 2 --

CREATE TABLE DOKUMENTYSZCZEGOLY(
ID INT PRIMARY KEY,
IDTOWARU INT NOT NULL,
IDDOKUMENTU INT NOT NULL,
NAZWATOWARU VARCHAR2(120) NOT NULL,
ILOSC NUMBER(12,6) NOT NULL,
JM VARCHAR2(5) NOT NULL,
CENABRUTTO NUMBER(12,2) NOT NULL,
CENANETTO NUMBER(12,2) NOT NULL,
STAWKAVAT INT NOT NULL
);

-- 3 -- 
CREATE TABLE FIRMA(
ID INT PRIMARY KEY,
NAZWAFIRMY VARCHAR2(150) NOT NULL,
MIEJSCOWOSC VARCHAR2(100) NOT NULL,
KODPOCZTOWY VARCHAR2(6) NOT NULL,
ULICA VARCHAR2(100) NOT NULL,
NRBUDYNKU VARCHAR2(10) NOT NULL,
NIP INT NOT NULL,
REGON INT NOT NULL,
BANK VARCHAR2(100) NOT NULL,
NRRACHUNKU INT NOT NULL
);

-- 4 --
CREATE TABLE TOWARY(
ID INT PRIMARY KEY,
NAZWATOWARU VARCHAR2(120) NOT NULL,
CENABRUTTO NUMBER(12,2),
CENANETTO NUMBER(12,2),
STAWKAVAT INT NOT NULL,
JM INT NOT NULL,
SYMBOL VARCHAR2(20) NOT NULL UNIQUE
);

-- 5 --
CREATE TABLE JEDNOSTKIMIARY(
ID INT PRIMARY KEY,
JM VARCHAR2(5) NOT NULL,
PRECYZJA INT NOT NULL
);

-- 6 --
CREATE TABLE KONTRAHENCI(
ID INT PRIMARY KEY,
SKROTNAZWYFIRMY VARCHAR2(10) NOT NULL UNIQUE,
NAZWAFIRMY VARCHAR2(120),
IMIE VARCHAR2(80),
NAZWISKO VARCHAR2(80),
EMAIL VARCHAR2(100),
NRTELEFONU INT,
NIP INT,
PESEL INT,
MIEJSCOWOSC VARCHAR2(100) NOT NULL,
KODPOCZTOWY VARCHAR2(6) NOT NULL,
ULICA VARCHAR2(80),
NRBUDYNKU VARCHAR2(10) NOT NULL,
BANK VARCHAR2(100),
NRKONTA INT,
UWAGI VARCHAR2(200)
);

-- 7 --
CREATE TABLE LOGOWANIE(
ID INT PRIMARY KEY,
IDUZYTKOWNIKA INT NOT NULL,
LOGIN TIMESTAMP,
LOGOUT TIMESTAMP);

-- 8 --
CREATE TABLE STAWKAVAT(
ID INT PRIMARY KEY,
NAZWASTAWKI VARCHAR2(10),
STAWKAVAT INT
);

-- 9 --
CREATE TABLE UZYTKOWNICY(
ID INT PRIMARY KEY,
IDFIRMY INT NOT NULL,
NAZWAUZYTKOWNIKA VARCHAR2(100) NOT NULL UNIQUE,
IMIE VARCHAR2(80) NOT NULL,
NAZWISKO VARCHAR2(80) NOT NULL,
HASLO VARCHAR2(60) NOT NULL
);

-- tabele archiwum -- 
-- 10 --
CREATE TABLE ARCHIWUMTOWARY(
ID INT PRIMARY KEY,
NAZWAUZYTKOWNIKA VARCHAR2(100),
TYPDZIALANIA VARCHAR2(20),
DATA DATE,
S_NAZWATOWARU VARCHAR2(120),
S_CENABRUTTO NUMBER(12,2),
S_CENANETTO NUMBER(12,2),
S_STAWKAVAT INT,
S_JM INT,
S_SYMBOL VARCHAR2(20),
N_NAZWATOWARU VARCHAR2(120),
N_CENABRUTTO NUMBER(12,2),
N_CENANETTO NUMBER(12,2),
N_STAWKAVAT INT,
N_JM INT,
N_SYMBOL VARCHAR2(20)
);

-- 11 --
CREATE TABLE ARCHIWUMKONTRAHENCI(
ID INT PRIMARY KEY,
NAZWAUZYTKOWNIKA VARCHAR2(100),
TYPDZIALANIA VARCHAR2(20),
DATA DATE,
S_SKROTNAZWYFIRMY VARCHAR2(10),
S_NAZWAFIRMY VARCHAR2(120),
S_IMIE VARCHAR2(80),
S_NAZWISKO VARCHAR2(80),
S_EMAIL VARCHAR2(100),
S_NRTELEFONU VARCHAR2(11),
S_NIP INT,
S_PESEL INT,
S_MIEJSCOWOSC VARCHAR2(100),
S_KODPOCZTOWY VARCHAR2(6),
S_ULICA VARCHAR2(80),
S_NRBUDYNKU VARCHAR2(10),
S_BANK VARCHAR2(100),
S_NRKONTA INT,
S_UWAGI VARCHAR2(200),
N_SKROTNAZWYFIRMY VARCHAR2(10),
N_NAZWAFIRMY VARCHAR2(120),
N_IMIE VARCHAR2(80),
N_NAZWISKO VARCHAR2(80),
N_EMAIL VARCHAR2(100),
N_NRTELEFONU VARCHAR2(11),
N_NIP INT,
N_PESEL INT,
N_MIEJSCOWOSC VARCHAR2(100),
N_KODPOCZTOWY VARCHAR2(6),
N_ULICA VARCHAR2(80),
N_NRBUDYNKU VARCHAR2(10),
N_BANK VARCHAR2(100),
N_NRKONTA INT,
N_UWAGI VARCHAR2(200)
);

-- 12 --
CREATE TABLE ARCHIWUMUZYTKOWNICY(
ID INT PRIMARY KEY,
NAZWAUZYTKOWNIKA VARCHAR2(100),
TYPDZIALANIA VARCHAR2(20),
DATA DATE,
S_NAZWAUZYTKOWNIKA VARCHAR2(100),
S_IMIE VARCHAR2(80),
S_NAZWISKO VARCHAR2(80),
S_HASLO VARCHAR2(60),
N_NAZWAUZYTKOWNIKA VARCHAR2(100),
N_IMIE VARCHAR2(80),
N_NAZWISKO VARCHAR2(80),
N_HASLO VARCHAR2(60)
);

-- 13 --
CREATE TABLE ARCHIWUMDOKUMENTY(
ID int primary key,
NAZWAUZYTKOWNIKA VARCHAR2(100),
TYPDZIALANIA VARCHAR2(20),
DATA DATE,
S_NRFAKTURY varchar2(20),
S_TYPPLATNOSCI varchar2(50),
S_DATASPRZEDAZY date,
S_DATAFAKTURY date,
S_UWAGI varchar2(200),
    
N_NRFAKTURY varchar2(20),
N_TYPPLATNOSCI varchar2(50),
N_DATASPRZEDAZY date,
N_DATAFAKTURY date,
N_UWAGI varchar2(200)
);

-- 14 --
CREATE TABLE ARCHIWUMDOKUMENTYSZCZ(
ID INT PRIMARY KEY,
NAZWAUZYTKOWNIKA VARCHAR2(100),
TYPDZIALANIA VARCHAR2(20),
DATA DATE,
S_IDTOWARU INT,
S_IDDOKUMENTU INT,
S_NAZWATOWARU VARCHAR2(120),
S_ILOSC NUMBER(12,6),
S_JM VARCHAR2(5),
S_CENABRUTTO NUMBER(12,2),
S_CENANETTO NUMBER(12,2),
S_STAWKAVAT INT,
N_IDTOWARU INT,
N_IDDOKUMENTU INT,
N_NAZWATOWARU VARCHAR2(120),
N_ILOSC NUMBER(12,6),
N_JM VARCHAR2(5),
N_CENABRUTTO NUMBER(12,2),
N_CENANETTO NUMBER(12,2),
N_STAWKAVAT INT
);