-- 1 --
ALTER TABLE DOKUMENTY
ADD CONSTRAINT FK_DOK_KONTRAHENT FOREIGN KEY(IDKONTRAHENTA)
REFERENCES KONTRAHENCI(ID);

-- 2 --
ALTER TABLE DOKUMENTY
ADD CONSTRAINT FK_DOK_UZYTKOWNIK FOREIGN KEY(IDUZYTKOWNIKA)
REFERENCES UZYTKOWNICY(ID);

-- 3 --
ALTER TABLE DOKUMENTYSZCZEGOLY
ADD CONSTRAINT FK_DOKSZCZ_DOK FOREIGN KEY(IDDOKUMENTU)
REFERENCES DOKUMENTY(ID);

-- 4 --
ALTER TABLE DOKUMENTYSZCZEGOLY
ADD CONSTRAINT FK_DOKSZCZ_TOWAR FOREIGN KEY(IDTOWARU)
REFERENCES TOWARY(ID);

-- 5 --
ALTER TABLE TOWARY
ADD CONSTRAINT FK_TOWAR_JM FOREIGN KEY(JM)
REFERENCES JEDNOSTKIMIARY(ID);

-- 6 --
ALTER TABLE TOWARY
ADD CONSTRAINT FK_TOWAR_VAT FOREIGN KEY(STAWKAVAT)
REFERENCES STAWKAVAT(ID);

-- 7 --
ALTER TABLE UZYTKOWNICY
ADD CONSTRAINT FK_UZYT_FIRMA FOREIGN KEY(IDFIRMY)
REFERENCES FIRMA(ID);

-- 8 --
ALTER TABLE LOGOWANIE
ADD CONSTRAINT FK_LOG_UZYT FOREIGN KEY(IDUZYTKOWNIKA)
REFERENCES UZYTKOWNICY(ID);