-- 1 --
CREATE SEQUENCE DOKUMENTY_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 2 --
CREATE SEQUENCE DOKUMENTYSZCZEGOLY_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 3 --
CREATE SEQUENCE JEDNOSTKIMIARY_SEQ
	INCREMENT BY 10
	START WITH 10
;

-- 4 --
CREATE SEQUENCE KONTRAHENCI_SEQ
	INCREMENT BY 100
	START WITH 1000
;

-- 5 --
CREATE SEQUENCE LOGOWANIE_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 6 --
CREATE SEQUENCE STAWKAVAT_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 7 --
CREATE SEQUENCE TOWARY_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 8 --
CREATE SEQUENCE UZYTKOWNICY_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 9 --
CREATE SEQUENCE ARCHIWUMKONTRAHENCI_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 10 --
CREATE SEQUENCE ARCHIWUMTOWARY_SEQ
	INCREMENT BY 1
	START WITH 1
;

-- 11 --
CREATE SEQUENCE ARCHIWUMUZYTKOWNICY_SEQ
	INCREMENT BY 1
	START WITH 1
;
-- 12 --
CREATE SEQUENCE ARCHIWUMDOKUMENTY_SEQ
	INCREMENT BY 1
	START WITH 1
;
-- 13 --
CREATE SEQUENCE ARCHIWUMDOKUMENTYSZCZEGOLY_SEQ
	INCREMENT BY 1
	START WITH 1
;